title: SounderPy
description: Vertical Profile Data Retrieval Tool for Python
theme: just-the-docs

url: https://kylejgillett.github.io/sounderpy

aux_links:
  Template Repository: https://github.com/kylejgillett/sounderpy
